### ISSUE TITLE
Static route "/admin" error

### ISSUE THREAD

**Issue by 1f7** [aimeos/aimeos-slim#4]
After `composer update` and all setup steps try inter site but get **Slim Application Error**

``` php
Slim Application Error

The application could not run because of the following error:
Details
Type: FastRoute\BadRouteException
Message: Static route "/admin" is shadowed by previously defined variable route "/([^/]+)" for method "GET"
File: /var/www/test.local/slimfm/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php
Line: 64
Trace

#0 /var/www/test.local/slimfm/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php(18): FastRoute\DataGenerator\RegexBasedAbstract->addStaticRoute('GET', Array, 'route1')
#1 /var/www/test.local/slimfm/vendor/nikic/fast-route/src/RouteCollector.php(33): FastRoute\DataGenerator\RegexBasedAbstract->addRoute('GET', Array, 'route1')
#2 /var/www/test.local/slimfm/vendor/slim/slim/Slim/Router.php(159): FastRoute\RouteCollector->addRoute(Array, '/admin', 'route1')
#3 /var/www/test.local/slimfm/vendor/nikic/fast-route/src/functions.php(24): Slim\Router->Slim\{closure}(Object(FastRoute\RouteCollector))
#4 /var/www/test.local/slimfm/vendor/slim/slim/Slim/Router.php(162): FastRoute\simpleDispatcher(Object(Closure), Array)
#5 /var/www/test.local/slimfm/vendor/slim/slim/Slim/Router.php(146): Slim\Router->createDispatcher()
#6 /var/www/test.local/slimfm/vendor/slim/slim/Slim/App.php(511): Slim\Router->dispatch(Object(Slim\Http\Request))
#7 /var/www/test.local/slimfm/vendor/slim/slim/Slim/App.php(435): Slim\App->dispatchRouterAndPrepareRoute(Object(Slim\Http\Request), Object(Slim\Router))
#8 /var/www/test.local/slimfm/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /var/www/test.local/slimfm/vendor/slim/slim/Slim/App.php(337): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 /var/www/test.local/slimfm/vendor/slim/slim/Slim/App.php(298): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 /var/www/test.local/slimfm/public/index.php(32): Slim\App->run()
#12 {main}
```

**Comment by aimeos** [comment]
The Slim skeleton generator creates a test route for `/{name}` which you have to remove

**Comment by 1f7** [comment]
commen all in `src/routes.php`

``` php
<?php
// Routes

//$app->get('/[{name}]', function ($request, $response, $args) {
    // Sample log message
//    $this->logger->info("Slim-Skeleton '/' route");

    // Render index view
//    return $this->renderer->render($response, 'index.phtml', $args);
//});
```

try
http://test.local/slimfm/
http://test.local/slimfm/admin

> Page Not Found
> The page you are looking for could not be found. Check the address bar
